SELECT
    ca.LE_BOOK,
    ca.YEAR_MONTH,
    ast.ALPHA_SUBTAB_DESCRIPTION AS CAR_LINE_CODE_DESC,
    SUM(ca.VALUE_LCY) AS VALUE_LCY
FROM vision.CAPITAL_AR ca
LEFT JOIN vision.ALPHA_SUB_TAB ast
    ON ast.ALPHA_TAB = 5005
   AND ast.ALPHA_SUB_TAB = ca.CAR_LINE_CODE
GROUP BY ca.LE_BOOK, ca.YEAR_MONTH, ast.ALPHA_SUBTAB_DESCRIPTION
ORDER BY ca.LE_BOOK, ca.YEAR_MONTH, ast.ALPHA_SUBTAB_DESCRIPTION
