SELECT
    l.FRL_LINE,
    l.FRL_DESCRIPTION AS FRL_LINE_DESCRIPTION,
    l.FRL_SHORT_DESC,
    l.FRL_ATTRIBUTE_01,
    a.FRL_ATTRIBUTE_DESCRIPTION 
FROM vision.FRL_LINES l
LEFT JOIN vision.FRL_ATTRIBUTES a
    ON l.FRL_ATTRIBUTE_01 = a.FRL_ATTRIBUTE
--WHERE  a.FRL_ATTRIBUTE_DESCRIPTION = 'ASSETS' /* Total Assets */

-- SELECT *
-- FROM VISION.GL_CODES
-- WHERE LE_BOOK BETWEEN '400' AND '999'
-- AND GL_TYPE = '10'
-- AND ROWNUM <= 10;