SELECT LE_BOOK,
     LEB_DESCRIPTION,
      CATEGORY_TYPE_AT, 
      CATEGORY_TYPE, 
      YEAR_END_YTD_PL_GL, 
      LEB_STATUS_NT, 
      LEB_STATUS, 
      INTERNAL_STATUS, 
      DATE_LAST_MODIFIED, 
      DATE_CREATION, 
      LEB_SHORT_DESCRIPTION
FROM VISION.LE_BOOK
WHERE CATEGORY_TYPE IN ('MF','SACCO','OSACCO','DSACCO')